<?php
class Urm_model extends CI_Model {
    public function get_dash() {
        $asd= "'".implode("', '", array_unique($_SESSION['urm']))."'";
        $query_dash = "SELECT A.PROPNO,A.NAME,NVL(AGE,ROUND(MONTHS_BETWEEN(SYSDATE,DOB)/12)) age,DOB,PROPDAT,PLANNAME||' ('||P.PLAN||')' PLAN,TERM
FROM IPL.ALL_PROPOSAL A,IPL.PLAN P, IPL.EDUCATION E, IPL.OCCUP O, IPL.AGEPROOF B
WHERE A.PLAN=P.PLAN AND A.EDCODE=E.EDCODE AND A.OCCUP=O.OCCUP AND A.APC=B.APC AND  A.POLICY IS NULL
 and A.DATCOM<= trunc(sysdate) and A.DATCOM >= trunc(sysdate - 1)
and a.propno not in (select propno from  IPL.UNDERWRITING )";
        $q_dash = $this->db->query($query_dash)->result();
        return $q_dash;
    }
    public function get_urm() {
        $prop= $_GET['prop'];
        $query_prop = "SELECT A.PROPNO,A.EDCODE,P.PLAN PLAN1,A.NAME,NVL(AGE,ROUND(MONTHS_BETWEEN(SYSDATE,DOB)/12)) age,DOB,PROPDAT,PLANNAME||' ('||P.PLAN||')' PLAN,TERM,DECODE(PAYMODE,0,'SINGLE',1,'YEARLY',2,'HALF-YEARLY',4,'QUERTERLY',5,'MONTHLY') PAYMODE,DECODE(SEX,'M','MALE','F','FEMALE') SEX,DECODE(UR,'R','RURAL','U','URBAN','F','FOREIGN','NON-RESIDENCE') UR,
UPPER(EDNAME) EDCODE,OCCUPNAME OCCUP,APC_NAME APC,SUMASS,SUMRISK,DECODE(MEDICAL,1,'MEDICAL','2','NON-MEDICAL') MEDICAL,DECODE(A.POLICY_TYPE,'D','DOCUMENT','PASSBOOK') POLICY_TYPE,
NVL(SPREM1,0) SPREM1,NVL(SPREM2,0) SPREM2,NVL(SPREM3,0) SPREM3,NVL(SPREM4,0) SPREM4,NVL(SPREM5,0) SPREM5,NVL(SPREM6,0) SPREM6,
NVL(EXTPREM1,0)+NVL(EXTPREM2,0)+NVL(EXTPREM3,0) EXTPREM,
NVL(EXTSUM1,0)+NVL(EXTSUM2,0)+NVL(EXTSUM3,0)+NVL(EXTSUM4,0)+NVL(EXTSUM5,0)+NVL(EXTSUM6,0) EXTSUM,
NVL(EXTSUM,0) EXTSUMRISK,A.APU,A.APREM,A.DATCOM,A.PNEXTPAY,NVL(LPREM,0) LPREM,
NVL(EXTSUM1,0) EXTSUM1, NVL(EXTSUM2,0) EXTSUM2, NVL(EXTSUM3,0) EXTSUM3, NVL(EXTSUM4,0) EXTSUM4, NVL(EXTSUM5,0) EXTSUM5, NVL(EXTSUM6,0) EXTSUM6,
extcode1,EXTRATE1,extcode2,NVL(EXTPREM1,0) EXTPREM1 ,NVL(EXTPREM2,0) EXTPREM2, NVL(EXTPREM3,0) EXTPREM3, LTRIM(RTRIM(A.LIENCODE)) LIENCODE,LTRIM(RTRIM(A.REM1)) REM1
FROM IPL.ALL_PROPOSAL A,IPL.PLAN P, IPL.EDUCATION E, IPL.OCCUP O, IPL.AGEPROOF B
WHERE A.PLAN=P.PLAN AND A.EDCODE=E.EDCODE AND A.OCCUP=O.OCCUP AND A.APC=B.APC AND  POLICY IS NULL
and PROPNO='$prop'";
        $q_prop = $this->db->query($query_prop)->result();
        
        return $q_prop;
    }
}
