<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$route['default_controller'] = 'site';
$route['ep'] = 'site/ep';
$route['parinfo'] = 'site/parinfo';
$route['calprem'] = 'site/calprem';
$route['supli'] = 'site/supli';
$route['premcal'] = 'site/premcal';
$route['personalinfo']= 'site/personalinfo';
$route['propformnom']= 'site/propformnom';
$route['appdata'] = 'site/appdata';
$route['childprotection'] = 'site/childprotection';
$route['formhiin'] = 'site/formhiin';
$route['mchecklist'] = 'site/mchecklist';
$route['vform'] = 'site/vform';
$route['formbody'] = 'site/formbody';
$route['formedit'] = 'site/formedit';
$route['process'] = 'site/process';
$route['urm'] = 'site/urm';
$route['urmrep'] = 'site/urmrep';
$route['urmdash'] = 'site/urmdash';
$route['pppdf'] = 'site/pppdf';
$route['404_override'] = '';